site_name: Unbiased Hamiltonian Monte Carlo

theme:
  name: material
  features:
    - navigation.sections  # Sections are included in the navigation on the left.
    - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.

extra_css:
  - _static/custom.css

markdown_extensions:
    - admonition
    - toc:
        permalink: "⚓"  
        toc_depth: 4

plugins:
- search
- autorefs  
- mkdocstrings:
    handlers:
      python:
        options:
          separate_signature: true
          show_signature_annotations: true
          show_root_heading: true  
          show_root_full_path: false  
          heading_level: 4